#    Copyright 2018 Google Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        https://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: yaml
  version: "3.10"
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: "1.1.7"
- name: lxml
  version: "2.3"
- name: ssl
  version: latest

env_variables:
  DFP_API_VERSION: 'v201711'
  DFP_APP_NAME: 'x5'
  DEBUG: '1'

handlers:
- url: /favicon.ico$
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt$
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
  http_headers:
    X-Clacks-Overhead: GNU Terry Pratchett
- url: /admin/.*
  script: admin_handlers.app
  secure: always
  login: admin
- url: /.*
  script: main.app
  secure: always
  login: required

################################################################################
skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.pyo
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
